<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <RootNamespace>Axl.Base.Json.Legacy</RootNamespace>
    <AssemblyName>Axl.Base.Json.Legacy</AssemblyName>
    
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.Json.Legacy</PackageId>
    <Version>1.1.2</Version>
    <Authors>Axl</Authors>
    <Description>Legacy JSON processing library for backward compatibility.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>
</Project>

