<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <AssemblyName>Axl.Base.MqttNet</AssemblyName>
    <RootNamespace>Axl.Base.MqttNet</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.1.11</Version>
    <Authors>Axl</Authors>
    <Description>High-performance MQTT client using MqttNet.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.3.3.952" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>

</Project>

