<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RootNamespace>Axl.Base.Database.MSSQL</RootNamespace>
    <AssemblyName>Axl.Base.Database.MSSQL</AssemblyName>
    
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.Database.MSSQL</PackageId>
    <Version>1.1.11</Version>
    <Authors>Axl</Authors>
    <Description>Database access components for Microsoft SQL Server integration.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>

