<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Axl.Base.OpcUa</RootNamespace>
    <AssemblyName>Axl.Base.OpcUa</AssemblyName>
    
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.OpcUa</PackageId>
    <Version>1.1.2</Version>
    <Authors>Axl</Authors>
    <Description>OPC UA (Unified Architecture) client integration library.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.378.134" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>
</Project>

