<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RootNamespace>Axl.Base.Compression.Native</RootNamespace>
    <AssemblyName>Axl.Base.Compression.Native</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.Compression.Native</PackageId>
    <Version>1.1.2</Version>
    <Authors>Axl</Authors>
    <Description>Lightweight compression library using native System.IO.Compression. Supports Zip and GZip.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>
</Project>
