<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RootNamespace>Axl.Base.Historian.WW</RootNamespace>
    <AssemblyName>Axl.Base.Historian.WW</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.Historian.WW</PackageId>
    <Version>1.0.0</Version>
    <Authors>Axl</Authors>
    <Description>Library for Wonderware Historian integration using MSSQL.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
