<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <RootNamespace>Axl.Base.Wmi</RootNamespace>
    <AssemblyName>Axl.Base.Wmi</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.Wmi</PackageId>
    <Version>1.1.6</Version>
    <Authors>Axl</Authors>
    <Description>WMI (Windows Management Instrumentation) query and management library.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
  </ItemGroup>
</Project>


