<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <RootNamespace>Axl.Base.RegistryStore</RootNamespace>
    <AssemblyName>Axl.Base.RegistryStore</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.RegistryStore</PackageId>
    <Version>1.0.0</Version>
    <Authors>Axl</Authors>
    <Description>Windows Registry secure secret store using DPAPI.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>
</Project>
