<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <RootNamespace>Axl.Base.Mqtt</RootNamespace>
    <AssemblyName>Axl.Base.Mqtt</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Axl.Base.Mqtt</PackageId>
    <Version>1.1.10</Version>
    <Authors>Axl</Authors>
    <Description>MQTT protocol client integration library.</Description>
    <PackageOutputPath>c:\Users\Axl\Desktop\Projects\LocalNugetFeed</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axl.Base.Common\Axl.Base.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="M2Mqtt" Version="3.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>


